spring:
  application:
    name: service-zuul

server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: service-feign
  ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000
