server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/chao8449139/chao.git
          search-paths: springcloud*
          username: chao8449139
          password: chen8449139
